#!/bin/sh
set -eu

mkdir -p \
  /app/runtime/config \
  /app/runtime/data/db \
  /app/runtime/data/static \
  /app/runtime/data/media

python - <<'PY'
from pathlib import Path

from django.core.management.utils import get_random_secret_key

env_file = Path("/app/runtime/config/.env")


def parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in raw_line:
            continue

        key, value = raw_line.split("=", 1)
        key = key.strip()
        value = value.strip()

        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]

        values[key] = value

    return values


def write_env_file(path: Path, values: dict[str, str]) -> None:
    lines = [
        "# Generated by Mylonite on first start.",
        "# This file is local to this instance and should not be committed.",
        f'DJANGO_SECRET_KEY={values["DJANGO_SECRET_KEY"]}',
        f'DJANGO_DEBUG={values.get("DJANGO_DEBUG", "false")}',
    ]

    if values.get("DJANGO_SECRET_KEY_FALLBACKS"):
        lines.append(f'DJANGO_SECRET_KEY_FALLBACKS={values["DJANGO_SECRET_KEY_FALLBACKS"]}')

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(0o600)


def update_env_file(path: Path, updates: dict[str, str]) -> None:
    lines = path.read_text(encoding="utf-8").splitlines()
    new_lines: list[str] = []
    updated_keys: set[str] = set()

    for raw_line in lines:
        line = raw_line.strip()
        if line and not line.startswith("#") and "=" in raw_line:
            key, _ = raw_line.split("=", 1)
            key = key.strip()

            if key in updates:
                new_lines.append(f"{key}={updates[key]}")
                updated_keys.add(key)
                continue

        new_lines.append(raw_line)

    for key, value in updates.items():
        if key not in updated_keys:
            new_lines.append(f"{key}={value}")

    path.write_text("\n".join(new_lines).rstrip() + "\n", encoding="utf-8")
    path.chmod(0o600)


values = parse_env_file(env_file)
updates: dict[str, str] = {}

if not values.get("DJANGO_SECRET_KEY", "").strip():
    updates["DJANGO_SECRET_KEY"] = get_random_secret_key()

if not env_file.exists():
    updates["DJANGO_DEBUG"] = values.get("DJANGO_DEBUG", "false") or "false"
    write_env_file(env_file, {**values, **updates})
    print("Generated runtime/config/.env with a unique Django secret key.")
elif updates:
    update_env_file(env_file, updates)
    print("Updated runtime/config/.env with a generated Django secret key.")
else:
    try:
      env_file.chmod(0o600)
    except PermissionError:
      pass
PY

python manage.py migrate --noinput
python manage.py collectstatic --noinput

exec "$@"
