from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from tempfile import NamedTemporaryFile


@dataclass(frozen=True)
class RuntimePaths:
    config_root: Path
    data_root: Path
    db_path: Path
    static_root: Path
    media_root: Path


def resolve_runtime_paths(base_dir: Path) -> RuntimePaths:
    config_root = Path(
        os.getenv("MYLONITE_CONFIG_ROOT", base_dir / "runtime" / "config")
    )
    data_root = Path(os.getenv("MYLONITE_DATA_ROOT", base_dir / "runtime" / "data"))
    db_path = Path(os.getenv("MYLONITE_DB_PATH", data_root / "db" / "mylonite.sqlite3"))

    return RuntimePaths(
        config_root=config_root,
        data_root=data_root,
        db_path=db_path,
        static_root=data_root / "static",
        media_root=data_root / "media",
    )


RUNTIME_ENV_HEADER = [
    "# Generated by Mylonite on first start.",
    "# This file is local to this instance and should not be committed.",
]


def load_simple_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    values: dict[str, str] = {}

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in raw_line:
            continue

        key, value = raw_line.split("=", 1)
        key = key.strip()
        value = value.strip()

        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]

        values[key] = value

    return values


def safe_chmod(path: Path, mode: int) -> None:
    try:
        path.chmod(mode)
    except PermissionError:
        pass
    except OSError:
        pass


def atomic_write_text(path: Path, content: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    temp_path: Path | None = None

    try:
        with NamedTemporaryFile(
            "w",
            encoding="utf-8",
            dir=path.parent,
            delete=False,
        ) as handle:
            temp_path = Path(handle.name)
            handle.write(content)

        safe_chmod(temp_path, mode)
        temp_path.replace(path)
        safe_chmod(path, mode)
    finally:
        if temp_path is not None and temp_path.exists():
            try:
                temp_path.unlink()
            except OSError:
                pass


def write_simple_env(
    path: Path,
    values: dict[str, str],
    *,
    header_lines: list[str] | None = None,
) -> None:
    lines: list[str] = []
    if header_lines:
        lines.extend(header_lines)

    lines.extend(f"{key}={value}" for key, value in values.items())

    atomic_write_text(path, "\n".join(lines) + "\n", 0o600)


def update_simple_env(path: Path, updates: dict[str, str]) -> None:
    lines = path.read_text(encoding="utf-8").splitlines()
    new_lines: list[str] = []
    updated_keys: set[str] = set()

    for raw_line in lines:
        line = raw_line.strip()
        if line and not line.startswith("#") and "=" in raw_line:
            key, _ = raw_line.split("=", 1)
            key = key.strip()

            if key in updates:
                new_lines.append(f"{key}={updates[key]}")
                updated_keys.add(key)
                continue

        new_lines.append(raw_line)

    for key, value in updates.items():
        if key not in updated_keys:
            new_lines.append(f"{key}={value}")

    atomic_write_text(path, "\n".join(new_lines).rstrip() + "\n", 0o600)


def ensure_runtime_env_file(path: Path) -> tuple[bool, bool]:
    from django.core.management.utils import get_random_secret_key

    values = load_simple_env(path)

    if not path.exists():
        values = {
            "DJANGO_SECRET_KEY": values.get("DJANGO_SECRET_KEY")
            or get_random_secret_key(),
            "DJANGO_DEBUG": values.get("DJANGO_DEBUG", "false") or "false",
            **{
                key: value
                for key, value in values.items()
                if key not in {"DJANGO_SECRET_KEY", "DJANGO_DEBUG"}
            },
        }
        write_simple_env(path, values, header_lines=RUNTIME_ENV_HEADER)
        return True, False

    updates: dict[str, str] = {}
    if not values.get("DJANGO_SECRET_KEY", "").strip():
        updates["DJANGO_SECRET_KEY"] = get_random_secret_key()

    if updates:
        update_simple_env(path, updates)
        return False, True

    safe_chmod(path, 0o600)
    return False, False


def ensure_runtime_directories(paths: list[Path]) -> None:
    for path in paths:
        path.mkdir(parents=True, exist_ok=True)
