from __future__ import annotations

from pathlib import Path


RUNTIME_ENV_HEADER = [
    "# Generated by Mylonite on first start.",
    "# This file is local to this instance and should not be committed.",
]


def load_simple_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    values: dict[str, str] = {}

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in raw_line:
            continue

        key, value = raw_line.split("=", 1)
        key = key.strip()
        value = value.strip()

        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]

        values[key] = value

    return values


def safe_chmod(path: Path, mode: int) -> None:
    try:
        path.chmod(mode)
    except PermissionError:
        pass
    except OSError:
        pass


def write_simple_env(
    path: Path,
    values: dict[str, str],
    *,
    header_lines: list[str] | None = None,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    if header_lines:
        lines.extend(header_lines)

    lines.extend(f"{key}={value}" for key, value in values.items())

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    safe_chmod(path, 0o600)


def update_simple_env(path: Path, updates: dict[str, str]) -> None:
    lines = path.read_text(encoding="utf-8").splitlines()
    new_lines: list[str] = []
    updated_keys: set[str] = set()

    for raw_line in lines:
        line = raw_line.strip()
        if line and not line.startswith("#") and "=" in raw_line:
            key, _ = raw_line.split("=", 1)
            key = key.strip()

            if key in updates:
                new_lines.append(f"{key}={updates[key]}")
                updated_keys.add(key)
                continue

        new_lines.append(raw_line)

    for key, value in updates.items():
        if key not in updated_keys:
            new_lines.append(f"{key}={value}")

    path.write_text("\n".join(new_lines).rstrip() + "\n", encoding="utf-8")
    safe_chmod(path, 0o600)


def ensure_runtime_env_file(path: Path) -> tuple[bool, bool]:
    from django.core.management.utils import get_random_secret_key

    values = load_simple_env(path)
    created = False
    updated = False

    if not path.exists():
        values = {
            "DJANGO_SECRET_KEY": values.get("DJANGO_SECRET_KEY") or get_random_secret_key(),
            "DJANGO_DEBUG": values.get("DJANGO_DEBUG", "false") or "false",
            **{
                key: value
                for key, value in values.items()
                if key not in {"DJANGO_SECRET_KEY", "DJANGO_DEBUG"}
            },
        }
        write_simple_env(path, values, header_lines=RUNTIME_ENV_HEADER)
        return True, True

    updates: dict[str, str] = {}
    if not values.get("DJANGO_SECRET_KEY", "").strip():
        updates["DJANGO_SECRET_KEY"] = get_random_secret_key()

    if updates:
        update_simple_env(path, updates)
        updated = True
    else:
        safe_chmod(path, 0o600)

    return created, updated
